version: "3.9"

services:
  tests:
    build: .
    command: wrapped_cargo $ENGI_WORKING_DIR/results.txt
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
