version: "3.9"

services:
  tests:
    build: .
    #command: /bin/sh -c "echo $ENGI_WORKING_DIR; cargo test -- -Z unstable-options --format json | tee $ENGI_WORKING_DIR/results.txt"
    command: /bin/sh -c "env"
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
